# Generated by Django 4.2.1 on 2023-06-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesurvey', '0002_remove_question_pub_date_alter_survey_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='participant_email',
        ),
        migrations.AddField(
            model_name='survey',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
