# Generated by Django 4.2.1 on 2023-06-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesurvey', '0005_remove_submission_status_remove_submission_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='widget_type',
            field=models.CharField(choices=[('ST', 'Short question (max size 255 characters)'), ('LT', 'Paragraphs (max size 10,000 characters)'), ('DD', 'Dropdown'), ('MC', 'Multiple Choice'), ('SA', 'Single correct answer'), ('MA', 'Multiple correct answers'), ('CB', 'Checkboxes'), ('LS', 'Linear scale'), ('DT', 'Date'), ('TM', 'Time'), ('MCG', 'Multiple choice grid'), ('EM', 'Email'), ('NM', 'Numeric values')], default='RS', max_length=3),
        ),
    ]
