# Generated by Django 4.2.1 on 2023-06-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesurvey', '0006_alter_question_widget_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='date_answer',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='email_answer',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='integer_answer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='text_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='time_answer',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
