# Generated by Django 4.2.1 on 2023-06-03 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesurvey', '0007_submission_date_answer_submission_email_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='date_answer',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='email_answer',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='integer_answer',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='text_answer',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='time_answer',
        ),
        migrations.AlterField(
            model_name='submission',
            name='answer',
            field=models.ManyToManyField(related_name='answers', to='onlinesurvey.choice'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinesurvey.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='onlinesurvey.submission')),
            ],
        ),
    ]
