# Generated by Django 4.2.1 on 2023-06-03 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesurvey', '0009_answer_choice_answer_answer_date_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='numeric_answer',
            new_name='integer_answer',
        ),
    ]
