# Generated by Django 4.2.1 on 2023-06-03 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesurvey', '0011_remove_submission_answer_remove_answer_choice_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='choice_answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='choice_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlinesurvey.choice'),
        ),
    ]
