# Generated by Django 4.2.1 on 2023-06-04 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesurvey', '0014_remove_survey_questions_question_survey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='access_token',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='permissions',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='onlinesurvey.survey'),
        ),
        migrations.AlterField(
            model_name='question',
            name='widget_type',
            field=models.CharField(choices=[('ST', 'Short question (max size 255 characters)'), ('LT', 'Paragraphs (max size 10,000 characters)'), ('DD', 'Dropdown'), ('SA', 'Single correct answer'), ('CB', 'Checkboxes'), ('DT', 'Date'), ('TM', 'Time'), ('EM', 'Email'), ('NM', 'Numeric values')], default='RS', max_length=3),
        ),
        migrations.AlterField(
            model_name='submission',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinesurvey.survey'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
