# Generated by Django 4.2.1 on 2023-06-04 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesurvey', '0015_survey_access_token_survey_permissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DateAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_answer', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_answer', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='integerAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integer_answer', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShortAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_answer', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_answer', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='widget_type',
            field=models.CharField(choices=[('ST', 'Short question (max size 255 characters)'), ('LT', 'Paragraphs (max size 10,000 characters)'), ('DD', 'Dropdown'), ('SA', 'Single correct answer'), ('CB', 'Checkboxes'), ('DT', 'Date'), ('TM', 'Time'), ('EM', 'Email'), ('NM', 'Numeric values')], max_length=3),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.AddField(
            model_name='timeanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_answers', to='onlinesurvey.question'),
        ),
        migrations.AddField(
            model_name='timeanswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_answers', to='onlinesurvey.submission'),
        ),
        migrations.AddField(
            model_name='textanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_answers', to='onlinesurvey.question'),
        ),
        migrations.AddField(
            model_name='textanswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_answers', to='onlinesurvey.submission'),
        ),
        migrations.AddField(
            model_name='shortanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_answers', to='onlinesurvey.question'),
        ),
        migrations.AddField(
            model_name='shortanswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_answers', to='onlinesurvey.submission'),
        ),
        migrations.AddField(
            model_name='integeranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integer_answers', to='onlinesurvey.question'),
        ),
        migrations.AddField(
            model_name='integeranswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integer_answers', to='onlinesurvey.submission'),
        ),
        migrations.AddField(
            model_name='emailanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_answers', to='onlinesurvey.question'),
        ),
        migrations.AddField(
            model_name='emailanswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_answers', to='onlinesurvey.submission'),
        ),
        migrations.AddField(
            model_name='dateanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_answers', to='onlinesurvey.question'),
        ),
        migrations.AddField(
            model_name='dateanswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_answers', to='onlinesurvey.submission'),
        ),
        migrations.AddField(
            model_name='choiceanswer',
            name='choice_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlinesurvey.choice'),
        ),
        migrations.AddField(
            model_name='choiceanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_answers', to='onlinesurvey.question'),
        ),
        migrations.AddField(
            model_name='choiceanswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_answers', to='onlinesurvey.submission'),
        ),
    ]
