# Generated by Django 4.2.1 on 2023-06-04 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesurvey', '0016_choiceanswer_dateanswer_emailanswer_integeranswer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.CharField(blank=True, max_length=10000, null=True)),
                ('short_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('date_answer', models.DateField(blank=True, null=True)),
                ('time_answer', models.TimeField(blank=True, null=True)),
                ('email_answer', models.EmailField(blank=True, max_length=254, null=True)),
                ('integer_answer', models.IntegerField(blank=True, null=True)),
                ('choice_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlinesurvey.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='onlinesurvey.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='onlinesurvey.submission')),
            ],
        ),
        migrations.RemoveField(
            model_name='dateanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='dateanswer',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='emailanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='emailanswer',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='integeranswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='integeranswer',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='shortanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='shortanswer',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='textanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='textanswer',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='timeanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='timeanswer',
            name='submission',
        ),
        migrations.DeleteModel(
            name='ChoiceAnswer',
        ),
        migrations.DeleteModel(
            name='DateAnswer',
        ),
        migrations.DeleteModel(
            name='EmailAnswer',
        ),
        migrations.DeleteModel(
            name='integerAnswer',
        ),
        migrations.DeleteModel(
            name='ShortAnswer',
        ),
        migrations.DeleteModel(
            name='TextAnswer',
        ),
        migrations.DeleteModel(
            name='TimeAnswer',
        ),
    ]
